# Generated by Django 5.1.7 on 2026-08-15 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortCongestionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_waiting_hours', models.FloatField(default=12.0)),
                ('vessels_waiting', models.IntegerField(default=5)),
                ('vessels_berthing', models.IntegerField(default=3)),
                ('congestion_index', models.FloatField(default=0.25)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congestion_snapshots', to='masterdata.port')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=200)),
                ('transit_days', models.IntegerField(default=10)),
                ('distance_nm', models.FloatField(default=1000.0)),
                ('route_risk_score', models.FloatField(default=0.15)),
                ('congestion_score', models.FloatField(default=0.2)),
                ('composite_score', models.FloatField(default=0.85)),
                ('is_recommended', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=1)),
                ('agent_confidence', models.FloatField(default=0.92)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=1500.0, max_digits=12)),
                ('sub_scores', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_routes', to='masterdata.carrier')),
                ('destination_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_dest', to='masterdata.port')),
                ('origin_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_origin', to='masterdata.port')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='shipments.shipment')),
            ],
            options={
                'ordering': ['rank', '-composite_score'],
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leg_index', models.IntegerField(default=1)),
                ('vessel_name', models.CharField(blank=True, default='CMA CGM CHENNAI', max_length=150)),
                ('transit_days', models.IntegerField(default=5)),
                ('is_transhipment', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_carrier', to='masterdata.carrier')),
                ('from_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_from', to='masterdata.port')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='routing.route')),
                ('to_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_to', to='masterdata.port')),
            ],
            options={
                'ordering': ['leg_index'],
            },
        ),
        migrations.CreateModel(
            name='RoutePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lane_key', models.CharField(db_index=True, max_length=50)),
                ('on_time_pct', models.FloatField(default=90.0)),
                ('avg_transit_days', models.FloatField(default=7.0)),
                ('sample_count', models.IntegerField(default=50)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='masterdata.carrier')),
            ],
        ),
    ]
