# Generated by Django 5.1.7 on 2026-08-15 13:27

import apps.quotes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('routing', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=1)),
                ('condition_type', models.CharField(choices=[('MARGIN_BELOW_FLOOR', 'Margin Below Lane Policy Floor'), ('HIGH_VALUE', 'Total Quote Value Exceeds Threshold'), ('PREDICTED_RATES', 'Uncontracted Predicted Rates Used')], default='MARGIN_BELOW_FLOOR', max_length=50)),
                ('threshold_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('approver_role', models.CharField(choices=[('CUSTOMER', 'Customer / User'), ('BROKER', 'Freight Broker'), ('SENIOR_BROKER', 'Senior Broker'), ('PRICING_MANAGER', 'Pricing Manager'), ('OPERATIONS', 'Operations Lead'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('EXECUTIVE', 'Executive Management'), ('ADMIN', 'System Administrator')], default='SENIOR_BROKER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='MarginPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global Default Policy'), ('LANE', 'Trade Lane Specific Policy'), ('CUSTOMER_TIER', 'Customer Tier Specific Policy'), ('CARGO_TYPE', 'Cargo Type Specific Policy')], default='GLOBAL', max_length=30)),
                ('scope_key', models.CharField(blank=True, db_index=True, default='GLOBAL', max_length=100)),
                ('floor_pct', models.DecimalField(decimal_places=3, default=12.0, max_digits=6)),
                ('target_pct', models.DecimalField(decimal_places=3, default=18.0, max_digits=6)),
                ('stretch_pct', models.DecimalField(decimal_places=3, default=24.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreightQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(db_index=True, default=apps.quotes.models.generate_quote_number, max_length=30, unique=True)),
                ('current_version', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Quote'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('APPROVED', 'Approved by Authority'), ('REJECTED', 'Rejected by Approver'), ('ISSUED', 'Issued to Customer'), ('ACCEPTED', 'Accepted by Customer'), ('DECLINED', 'Declined by Customer'), ('EXPIRED', 'Validity Expired'), ('SUPERSEDED', 'Superseded by New Version')], db_index=True, default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_quotes', to='customers.customer')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.SmallIntegerField(default=1)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('fx_rate_date', models.DateField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('margin_pct', models.DecimalField(decimal_places=3, default=15.0, max_digits=6)),
                ('margin_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('final_quote', models.DecimalField(decimal_places=4, max_digits=14)),
                ('transit_days', models.SmallIntegerField(default=10)),
                ('risk_score', models.DecimalField(decimal_places=4, default=0.15, max_digits=5)),
                ('win_probability', models.DecimalField(decimal_places=4, default=0.75, max_digits=5)),
                ('valid_until', models.DateTimeField()),
                ('model_versions', models.JSONField(default=dict)),
                ('data_as_of', models.JSONField(default=dict)),
                ('assumptions', models.JSONField(default=list)),
                ('rationale', models.JSONField(default=dict)),
                ('cost_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_quote_versions', to='masterdata.carrier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.freightquote')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_versions', to='routing.route')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_included_in_sell_rate', models.BooleanField(default=True)),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quoteversion')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='PDF', max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quotes.quoteversion')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver_role', models.CharField(choices=[('CUSTOMER', 'Customer / User'), ('BROKER', 'Freight Broker'), ('SENIOR_BROKER', 'Senior Broker'), ('PRICING_MANAGER', 'Pricing Manager'), ('OPERATIONS', 'Operations Lead'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('EXECUTIVE', 'Executive Management'), ('ADMIN', 'System Administrator')], default='SENIOR_BROKER', max_length=30)),
                ('threshold_breached', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('decision', models.CharField(choices=[('PENDING', 'Pending Decision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='quotes.quoteversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['status'], name='quotes_frei_status_ca856f_idx'),
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['created_at'], name='quotes_frei_created_d409b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteversion',
            unique_together={('quote', 'version')},
        ),
    ]
