# Generated by Django 5.1.7 on 2026-08-15 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('rate_type', models.CharField(choices=[('CONTRACT', 'Long-term Contract Rate'), ('SPOT', 'Spot Market Rate'), ('TARIFF', 'Standard Public Tariff')], default='CONTRACT', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='masterdata.carrier')),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='masterdata.currency')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lane_key', models.CharField(db_index=True, max_length=50)),
                ('container_type', models.CharField(default='40HC', max_length=15)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('observed_at', models.DateField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.carrier')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('BAF', 'Bunker Adjustment Factor (Fuel)'), ('CAF', 'Currency Adjustment Factor'), ('THC', 'Terminal Handling Charge'), ('ISPS', 'International Ship & Port Security'), ('PSS', 'Peak Season Surcharge'), ('LSS', 'Low Sulphur Surcharge'), ('DOC', 'Documentation & BL Fee'), ('IHC', 'Inland Haulage Charge'), ('SEC', 'Security & Compliance Surcharge')], default='BAF', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('calculation_type', models.CharField(choices=[('FLAT', 'Flat Fixed Fee'), ('PER_CONTAINER', 'Rate Per Container'), ('PERCENT', 'Percentage of Base Freight'), ('PER_KG', 'Rate Per Kilogram'), ('PER_RT', 'Rate Per Revenue Ton')], default='FLAT', max_length=30)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('applies_to', models.JSONField(default=list)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='masterdata.currency')),
            ],
        ),
        migrations.CreateModel(
            name='RateCardLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_type', models.CharField(default='40HC', max_length=15)),
                ('base_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('min_charge', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='masterdata.currency')),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_dest', to='masterdata.port')),
                ('origin_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_origin', to='masterdata.port')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.ratecard')),
            ],
            options={
                'indexes': [models.Index(fields=['origin_port', 'destination_port', 'container_type'], name='pricing_rat_origin__9c6a24_idx')],
            },
        ),
    ]
