# Generated by Django 5.1.7 on 2026-08-15 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('service_type', models.CharField(default='Ocean', max_length=50)),
                ('reliability_score', models.FloatField(default=90.0)),
                ('on_time_pct', models.FloatField(default=88.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hs_code', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('cargo_type', models.CharField(default='GEN', max_length=30)),
                ('duty_rate_pct', models.DecimalField(decimal_places=2, default=7.5, max_digits=5)),
                ('is_restricted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('length_ft', models.FloatField(default=20.0)),
                ('width_ft', models.FloatField(default=8.0)),
                ('height_ft', models.FloatField(default=8.5)),
                ('max_payload_kg', models.IntegerField(default=28000)),
                ('tare_weight_kg', models.IntegerField(default=2300)),
                ('internal_cbm', models.FloatField(default=33.2)),
                ('is_reefer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(default='APAC', max_length=50)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(default='$', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=150)),
                ('port_rotation', models.JSONField(default=list)),
                ('frequency_days', models.IntegerField(default=7)),
                ('sailings_per_week', models.FloatField(default=1.0)),
                ('transit_days', models.IntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='masterdata.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, default='', max_length=4)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('has_cargo_terminal', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='masterdata.country')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('un_locode', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_transhipment_hub', models.BooleanField(default=False)),
                ('supported_modes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='masterdata.country')),
            ],
        ),
        migrations.CreateModel(
            name='PortDistance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nautical_miles', models.FloatField()),
                ('corridor_via', models.CharField(default='Direct', max_length=50)),
                ('from_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_out', to='masterdata.port')),
                ('to_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_in', to='masterdata.port')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('holiday_name', models.CharField(max_length=150)),
                ('is_holiday', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='masterdata.country')),
            ],
            options={
                'unique_together': {('country', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='masterdata.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='masterdata.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['un_locode'], name='masterdata__un_loco_ff4e40_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['city'], name='masterdata__city_590c78_idx'),
        ),
        migrations.AddIndex(
            model_name='portdistance',
            index=models.Index(fields=['from_port', 'to_port'], name='masterdata__from_po_cd17fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portdistance',
            unique_together={('from_port', 'to_port')},
        ),
    ]
