# Generated by Django 5.1.7 on 2026-08-15 13:27

import apps.shipments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, default=apps.shipments.models.generate_shipment_reference, max_length=30, unique=True)),
                ('origin_code', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('destination_code', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('origin_name', models.CharField(blank=True, default='', max_length=150)),
                ('destination_name', models.CharField(blank=True, default='', max_length=150)),
                ('pickup_address', models.TextField(blank=True, default='')),
                ('pickup_pin', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('delivery_pin', models.CharField(blank=True, default='', max_length=20)),
                ('ready_date', models.DateField()),
                ('required_delivery_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('OCEAN', 'Ocean Freight'), ('AIR', 'Air Freight'), ('GROUND_RAIL', 'Ground & Rail Freight'), ('EXPRESS_AIR', 'Express Air Courier')], default='OCEAN', max_length=30)),
                ('load_type', models.CharField(choices=[('FCL', 'Full Container Load'), ('LCL', 'Less than Container Load')], default='FCL', max_length=10)),
                ('incoterm', models.CharField(choices=[('EXW', 'Ex Works'), ('FCA', 'Free Carrier'), ('FOB', 'Free On Board'), ('CIF', 'Cost, Insurance and Freight'), ('CFR', 'Cost and Freight'), ('DAP', 'Delivered At Place'), ('DDP', 'Delivered Duty Paid')], default='FOB', max_length=10)),
                ('container_type', models.CharField(blank=True, default='40HC', max_length=15)),
                ('container_count', models.IntegerField(default=1)),
                ('gross_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volumetric_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('chargeable_units', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('chargeable_basis', models.CharField(default='PER_CONTAINER', max_length=30)),
                ('total_volume_cbm', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('un_number', models.CharField(blank=True, default='', max_length=20)),
                ('imo_class', models.CharField(blank=True, default='', max_length=20)),
                ('is_temperature_controlled', models.BooleanField(default=False)),
                ('temp_min_c', models.FloatField(blank=True, null=True)),
                ('temp_max_c', models.FloatField(blank=True, null=True)),
                ('needs_insurance', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('contact_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_company_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_country', models.CharField(blank=True, default='IN', max_length=2)),
                ('status', models.CharField(choices=[('ENQUIRY', 'Enquiry Created'), ('QUOTING', 'Quoting in Progress'), ('QUOTED', 'Quoted'), ('QUOTE_FAILED', 'Quote Generation Failed'), ('WON', 'Deal Won'), ('LOST', 'Deal Lost'), ('EXPIRED', 'Enquiry Expired'), ('CANCELLED', 'Enquiry Cancelled')], db_index=True, default='ENQUIRY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='customers.customer')),
                ('destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_dest_air', to='masterdata.airport')),
                ('destination_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_dest', to='masterdata.port')),
                ('origin_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_origin_air', to='masterdata.airport')),
                ('origin_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_origin', to='masterdata.port')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('CONTAINER', 'Shipping Container'), ('PALLET', 'Standard Pallet'), ('CARTON', 'Corrugated Carton / Box'), ('CRATE', 'Heavy Wooden Crate'), ('DRUM', 'Steel / Plastic Drum'), ('BAG', 'Industrial Sack / Bag'), ('LOOSE', 'Loose / Breakbulk Cargo')], default='CARTON', max_length=30)),
                ('commodity_description', models.CharField(max_length=255)),
                ('hs_code', models.CharField(blank=True, default='', max_length=12)),
                ('quantity', models.IntegerField(default=1)),
                ('weight_per_unit_kg', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('length_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_stackable', models.BooleanField(default=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment')),
            ],
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['origin_code', 'destination_code'], name='shipments_s_origin__b3c7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx'),
        ),
    ]
